#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $(basename "$0") --file EVENT_HANDLER [options...]

Options:
  -f, --file FILE  event handler file
  -h, --help       show this message
  -k, --kill       kill already started event handler
  -r, --reload     reload already started event handler
  -v, --verbose    show more output
EOF
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
then
  while [[ -n $* ]]
  do
    case "$1" in
      -h|--help)
        usage
        exit 0
        ;;
      -f|--file)
        EVENT_FILE="$2"
        shift 2
        ;;
      -k|--kill|--exit|--quit|--stop)
        ACTION="kill"
        shift
        ;;
      -r|--reload)
        ACTION="reload"
        shift
        ;;
      -v|--verbose)
        VERBOSE="--verbose"
        shift
        ;;
      --)
        shift
        break
        ;;
      *)
        echo "Unknown option: $1" >&2
        usage >&2
        exit 2
        ;;
    esac
  done

  if [[ -z "$EVENT_FILE" ]]
  then
    echo "Event handler not provided." >&2
    usage >&2
    exit 2
  fi

  if [[ ! -r "$EVENT_FILE" ]]
  then
    echo "Event handler not found: $EVENT_FILE" >&2
    exit 2
  fi

  EVENT_LOADER="$(dirname "$0")/event_loader"
  SELF="${EVENT_LOADER}.*${EVENT_FILE}"

  case "$ACTION" in
    kill)
      pkill -f "$SELF"
      exit "$?"
      ;;
    reload)
      pkill -USR1 -f "$SELF"
      exit "$?"
      ;;
    *)
      HYPRLAND_SOCKET="${TMPDIR:-/tmp}/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock"
      socat -u "UNIX-CONNECT:${HYPRLAND_SOCKET}" \
          EXEC:"$EVENT_LOADER $VERBOSE $EVENT_FILE",nofork
      ;;
  esac
fi
